apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: microsmack-ci-dev
  namespace: microsmack
spec:
  serviceAccountName: argo
  entrypoint: build-and-deploy-dev
  templates:
    - name: build-and-deploy-dev
      dag:
        tasks:
          - name: build-api-dev
            template: kaniko-build-api-dev
          - name: build-web
            template: kaniko-build-web
          - name: deploy-api-dev
            template: kubectl-apply-api-dev
            dependencies: [build-api-dev]
          - name: deploy-web
            template: kubectl-apply-web
            dependencies: [build-web]

    # Kaniko build API Dev
    - name: kaniko-build-api-dev
      container:
        image: gcr.io/kaniko-project/executor:debug
        command: [sh, -c]
        args:
          - |
            echo "Files in /workspace:" && ls -R /workspace && \
            /kaniko/executor \
              --dockerfile=Dockerfile \
              --context=/workspace/smackapi \
              --destination=docker.io/992220449/smackapi:dev \
              --cache=false
        envFrom:
          - secretRef:
              name: docker-credentials
        volumeMounts:
          - name: repo
            mountPath: /workspace
          - name: docker-config
            mountPath: /kaniko/.docker
            readOnly: true
      initContainers:
        - name: git-clone
          image: alpine/git
          command: ["sh", "-c"]
          args:
            - git clone --depth=1 --branch dev https://github.com/Zeta201/smack.git /workspace
          volumeMounts:
            - name: repo
              mountPath: /workspace

    # Kaniko build Web
    - name: kaniko-build-web
      container:
        image: gcr.io/kaniko-project/executor:debug
        command: ["sh", "-c"]
        args:
          - |
            echo "Files in /workspace:" && ls -R /workspace && \
            /kaniko/executor \
              --dockerfile=Dockerfile \
              --context=/workspace/web \
              --destination=docker.io/992220449/smackweb:latest \
              --cache=false
        envFrom:
          - secretRef:
              name: docker-credentials
        volumeMounts:
          - name: repo
            mountPath: /workspace
          - name: docker-config
            mountPath: /kaniko/.docker
            readOnly: true
      initContainers:
        - name: git-clone
          image: alpine/git
          command: ["sh", "-c"]
          args:
            - git clone --depth=1 --branch dev https://github.com/Zeta201/smack.git /workspace
          volumeMounts:
            - name: repo
              mountPath: /workspace

    # Deploy API Dev
    - name: kubectl-apply-api-dev
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      container:
        image: bitnami/kubectl:latest
        command: [sh, -c]
        args:
          - |
            kubectl apply -f /workspace/kubernetes/smackapi-dev-deployment.yaml -n microsmack && \
            kubectl rollout restart deployment/smackapi-dev -n microsmack
        volumeMounts:
          - name: repo
            mountPath: /workspace

    # Deploy Web
    - name: kubectl-apply-web
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      container:
        image: bitnami/kubectl:latest
        command: [sh, -c]
        args:
          - |
            set -ex
            kubectl apply -f /workspace/kubernetes/web-deployment.yaml -n microsmack
            kubectl apply -f /workspace/kubernetes/web-service.yaml -n microsmack
            kubectl rollout restart deployment/smackweb -n microsmack
        volumeMounts:
          - name: repo
            mountPath: /workspace

  volumes:
    - name: repo
      emptyDir: {}
    - name: docker-config
      secret:
        secretName: docker-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
