apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-events
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    example:
      owner: Zeta201
      repository: smack
      webhook:
        endpoint: /push
        port: "12000"
      events:
        - push
        - pull_request
      apiToken:
        name: github-secret
        key: token
