apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-events
  namespace: argo-events
spec:
  github:
    example:
      owner: Zeta201
      repository: smack
      webhook:
        endpoint: /push
        port: 12000
        secret:
          name: github-webhook-secret
          key: secret
      events:
        - push
        - pull_request
      apiToken:
        name: github-secret
        key: token
