apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: microsmack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
  namespace: microsmack
rules:
  # Argo CRD permissions
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates", "workflowtaskresults"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Kubernetes deployments and services
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-binding
  namespace: microsmack
subjects:
  - kind: ServiceAccount
    name: argo
    namespace: microsmack
roleRef:
  kind: Role
  name: argo-role
  apiGroup: rbac.authorization.k8s.io
