apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: microsmack-ci-template
  namespace: microsmack
spec:
  entrypoint: build-and-deploy
  templates:
    - name: build-and-deploy
      dag:
        tasks:
          - name: build-api
            template: kaniko-build-api
          - name: build-web
            template: kaniko-build-web
          - name: deploy-api
            template: kubectl-apply-api
            dependencies: [build-api]
          - name: deploy-web
            template: kubectl-apply-web
            dependencies: [build-web]

    # Kaniko build API
    - name: kaniko-build-api
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --dockerfile=smackapi/Dockerfile
          - --context=/workspace
          - --destination=$DOCKER_USER/smackapi:latest
          - --cache=true
        envFrom:
          - secretRef:
              name: docker-credentials
      volumeMounts:
        - name: repo
          mountPath: /workspace

    # Kaniko build Web
    - name: kaniko-build-web
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --dockerfile=web/Dockerfile
          - --context=/workspace
          - --destination=$DOCKER_USER/smackweb:latest
          - --cache=true
        envFrom:
          - secretRef:
              name: docker-credentials
      volumeMounts:
        - name: repo
          mountPath: /workspace

    # Deploy API
    - name: kubectl-apply-api
      container:
        image: bitnami/kubectl:latest
        command: [sh, -c]
        args:
          - kubectl apply -f smackapi-deployment.yaml -n microsmack
            && kubectl apply -f smackapi-service.yaml -n microsmack

    # Deploy Web
    - name: kubectl-apply-web
      container:
        image: bitnami/kubectl:latest
        command: [sh, -c]
        args:
          - kubectl apply -f web-deployment.yaml -n microsmack
            && kubectl apply -f web-service.yaml -n microsmack

  volumes:
    - name: repo
      gitRepo:
        repository: https://github.com/Zeta201/smack.git
        revision: main
        directory: .
