apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-ci-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: github-dep
      eventSourceName: github-events
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: microsmack-ci-
                namespace: microsmack
              spec:
                workflowTemplateRef:
                  name: microsmack-ci-template
